### ISSUE TITLE
no attribute 'DumpcapTimeoutError'

### ISSUE THREAD

**Issue by parmegv** [webfp/tor-browser-crawler#10]
[dumputils](https://github.com/webfp/tor-browser-crawler/blob/master/tbcrawler/dumputils.py#L59) thinks there is a DumpcapTimeoutError attribute in [common](https://github.com/webfp/tor-browser-crawler/blob/master/tbcrawler/common.py)

**Comment by parmegv** [comment]
[This PR](https://github.com/webfp/tor-browser-crawler/pull/11) addresses the problem that was causing this exception to happen.

**Comment by mjuarezm** [comment]
Fixed in commit 627088f239c88e57907020ce5908dd7b5da36f7a.
