### ISSUE TITLE
"main.py" is missing

### ISSUE THREAD

**Issue by zhangxiaobai12345** [webfp/tor-browser-crawler#36]

**Comment by tianchen-zhang** [comment]
If you check the commit history, you can find out that main.py was actually been moved to ./tbcrawler and was renamed as pytbcrawler.py. This file is the only python file with `if __name__ == '__main__'` in it except for the unit test files. It seems that the readme file has not been updated yet.

**Comment by gunesacar** [comment]
> If you check the commit history, you can find out that main.py was actually been moved to ./tbcrawler and was renamed as pytbcrawler.py. This file is the only python file with `if __name__ == '__main__'` in it except for the unit test files. It seems that the readme file has not been updated yet.

That's correct. I updated the README.

This repository is not maintained anymore and it extremely outdated.
If you need to automate Tor Browser please check  https://github.com/webfp/tor-browser-selenium
